name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joaoguimaraesalves/joaoguimaraesalves@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_is_snake: yes
          plugin_is_snake_github_user: ${{ github.repository_owner }}
          plugin_is_snake_github_repository: ${{ github.repository_owner }}
          plugin_is_snake_github_theme: dark
